### PR TITLE
Added php 7.3 to composer.json

### PR DESCRIPTION
**Pull request by bheindl**
Added php 7.3 support for composer installations

### CODE REVIEW

**Comment by codedge** [comment]
Is this package still maintained and PRs merged?
Would be nice to get this merged - PHP 7.2 is only getting security updates, 7.3 & 7.4 are the fully maintained versions.

I guess you already know ;)

**Comment by beyondmedia** [comment]
@hilrob With Magento 2.3.4 offering PHP 7.3 Support this is highly needed. We could either fork or ignore platform reqs.

**Comment by codedge** [comment]
Till PHP 7.3 might be supported here, I use the fork from @bheindl https://github.com/bheindl/magento2-paypal-plus which can be installed with PHP 7.3.

**Comment by icsdevs** [comment]
The fact this hasn't been merged in yet makes me think the module isn't being maintained anymore.  I believe ignoring platform reqs does work & it is actually compatible with php 7.3 already.

**Comment by codedge** [comment]
This has been fixed now. Maybe someone can close this PR then.

**Pull request closed without merging**
