### PR TITLE
Fix requested object's class name in constructor

### PR DESCRIPTION
**Pull request by pzlamaniec**

### CODE REVIEW

**Comment by thampe** [comment]
Hi, 

when do plan on merging this? The current version does not work, due to this error (Orders cannot be placed).

Thanks!

**Comment by nobodyMO** [comment]
A similar error is in /Controller/Webhooks/Index.php.
\Magento\Framework\Filesystem\DriverInterface $driver in the constructor is not allowed in magento 2.3.5 and results in an exception.

**Comment by codedge** [comment]
For now the only help is to pin the version to `1.3.1` - with that at least orders can be placed. With `1.3.2` no order can be placed due to this bug here, as @thampe already stated.

.. at least we got installment banners all over the place :facepalm:

**Comment by nobodyMO** [comment]
That's one solution. I created my own fork instead and fixed the bugs myself. Since the installation is done directly from Github anyway, this works so far. 
Unfortunately this is not the only bug.  The last change in the shipping cost calculation had also nice effects and we lost money. We have several shipping methods the customer can choose between. Orders over 50 Euro are free for standard shipping, but not with DHL.
The code change had led to the fact that the shipping costs was charged during the authorization process and then there were simply no shipping costs in the final request. Since the booking was closed by Paypal, we lost 6.99.
I also removed the banners from composer.json. The deactivation for the onpage checkout doesn't work and for average orders below 50 Euro a more than obtrusive banner for installment payments in checkout simply doesn't make sense.

**Comment by gaiterjones** [comment]
I think it is time we made a formal complaint to PayPal about this. PayPal were very keen for merchants to take up pui in Germany and for magento merchants to use the iWays m1/m2 modules. If iWays are no longer supporting it they need to ensure someone takes over responsibility for it, or give us other options.

**Comment by thampe** [comment]
I have received feedback from the iways support. The error was recognized and will be fixed in the coming weeks.

**Comment by DiDHack** [comment]
> I have received feedback from the iways support. The error was recognized and will be fixed in the coming weeks.

Weeks? Really? Fix for 15 seconds takes weeks? Great support! They even don't answer on support request...

**Comment by thampe** [comment]
As far as I can see this issue was resloved in the last release. Should we close the issue.

**Pull request closed without merging**
