### PR TITLE
Fix error during webhook execution

### PR DESCRIPTION
**Pull request by sprankhub**

### CODE REVIEW

**Comment by smycek** [comment]
Hey @sprankhub does your patch solve the issue with the broken webhook on Magento 2.3.6 on php 7.2.x?

**Comment by sprankhub** [comment]
I do not know which issue you have, but it indeed does solve one issue with the webhook execution.

**Comment by torhoehn** [comment]
Found a matching exception in our logfiles, applied this PR as composer patch, fixed the issue.

**Comment by gaiterjones** [comment]
> Found a matching exception in our logfiles, applied this PR as composer patch, fixed the issue.

@torhoehn Could you please post the exception error you were seeing and your version of Magento2 ?

**Comment by torhoehn** [comment]
@gaiterjones Magento 2.3.3-p1:
`[Wed Feb 17 14:13:32.835783 2021] [proxy_fcgi:error] [pid 23446:tid 139947608532736] [client 173.0.81.33:42850] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Cannot instantiate interface Magento\\Framework\\Filesystem\\DriverInterface in /var/www/share/<domain>/magento_live/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:116\nStack trace:\n#0 /var/www/share/<domain>/magento_live/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->createObject('Magento\\\\Framewo...', Array)\n#1 /var/www/share/<domain>/magento_live/vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\\Framework\\ObjectManager\\Factory\\Compiled->create('Magento\\\\Framewo...')\n#2 /var/www/share/<domain>/magento_live/vendor/magento/framework/ObjectManager/Factory/Compiled.php(79): Magento\\Framework\\ObjectManager\\Factory\\Compiled->get('Magento\\\\Framewo...')\n#3 /var/www/share/<domain>/magento_live/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\\Framework\\ObjectManager\\Factory\\Compiled->create('Iways\\\\P...'`

**Comment by sprankhub** [comment]
Thanks for adopting my fix without any credits or without saying thank you after months, @TheB3Rt0z! At least it is officially fixed now. Such a shame that one of the most important and biggest payment providers just does not care at all about support requests :-1:

**Pull request closed without merging**
